# Generated by Django 2.2.6 on 2019-10-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='classification',
            field=models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='app.Schools'),
        ),
    ]
