# Generated by Django 2.2.6 on 2019-10-05 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191005_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
