# Generated by Django 2.2.6 on 2019-10-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
            preserve_default=False,
        ),
    ]
