# Generated by Django 2.2.6 on 2019-10-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subject_category_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
            preserve_default=False,
        ),
    ]
