# Generated by Django 2.2.6 on 2019-10-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Subject'),
            preserve_default=False,
        ),
    ]
