# Generated by Django 2.2.6 on 2019-10-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191007_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='options',
        ),
    ]
