# Generated by Django 2.2.6 on 2019-10-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191009_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='options',
            new_name='option',
        ),
    ]
