# Generated by Django 2.2.6 on 2019-10-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191009_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questions',
            new_name='question',
        ),
    ]
