# Generated by Django 2.2.6 on 2019-10-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191009_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('---', '__'), ('انجليزي', 'انجليزي'), ('الرياضيات', 'الرياضيات'), ('العربيه', 'اللغه العربيه')], default='---', max_length=33),
        ),
        migrations.AlterField(
            model_name='profile',
            name='courses_taken',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(choices=[('---', '__'), ('المرحله\xa0الأبتدائيه', 'المرحله\xa0الأبتدائيه'), ('المرحله المتوسطه', 'المرحله المتوسطه'), ('المرحله\xa0الثانويه', 'المرحله\xa0الثانويه')], default='---', max_length=33),
        ),
    ]
